<nav class="header-menu">
    <a class="header-link" href="<?= BASE_URL ?>"><?= $index ?></a>
    <a class="header-link" href="<?= BASE_URL ?>?page=posts"><?= $posts ?></a>
    <a class="header-link" href="<?= BASE_URL ?>?page=calc"><?= $calc ?></a>
    <a class="header-link" href="<?= BASE_URL ?>?page=author"><?= $author ?></a>
    <a class="header-link" href="<?= BASE_URL ?>?page=theme"><?= $theme ?></a>
</nav>